#!/usr/bin/env node
// Writes every use case's "Scenarios (N)" view (4th button + panel) in overview.html from <plan>/use-cases.js, with Play
// links from the mock's play file (no play file → no links).
// Usage: node scenarios-panels.js <plan-dir> [--use-cases <file>] [--play-file <file>] [--play "<url with {id} {page} {state}>"] [--mock <index url>]

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const opt = (name, d) => { const i = args.indexOf(name); return i >= 0 ? args[i + 1] : d; };
const plan = args[0];
if (!plan) { process.stderr.write('usage: node scenarios-panels.js <plan-dir> [--use-cases <file>] [--play-file <file>] [--play <url>] [--mock <url>]\n'); process.exit(2); }
const ucFile = opt('--use-cases', path.join(plan, 'use-cases.js'));
const playFile = opt('--play-file', path.join(plan, 'mock/shared/scenario-play.js'));
const play = opt('--play', 'mock/index.html#sc-{id}');
const mockIndex = opt('--mock', 'mock/index.html');
const overviewPath = path.join(plan, 'overview.html');
let html = fs.readFileSync(overviewPath, 'utf8');
const fail = msg => { process.stderr.write(msg + '\n'); process.exit(1); };

/** `<NAME> = [ ... ]` parsed as strict JSON (works for `var X =` and `export const X =`). */
function parseVar(src, name, file) {
    const m = src.match(new RegExp(`\\b${name}\\s*=\\s*\\[`));
    if (!m) throw new Error(`${name} not found in ${file}`);
    const start = m.index + m[0].length - 1;
    let depth = 0, inStr = false;
    for (let j = start; j < src.length; j++) {
        const c = src[j];
        if (inStr) { if (c === '\\') j++; else if (c === '"') inStr = false; continue; }
        if (c === '"') inStr = true;
        else if (c === '[') depth++;
        else if (c === ']' && --depth === 0) return JSON.parse(src.slice(start, j + 1));
    }
    throw new Error(`${name}: unclosed array`);
}
const src = fs.readFileSync(ucFile, 'utf8');
// Plans made before the use case / scenario split group "use cases" under flows (3.N); they need a rebuild, not a patch.
if (/\bUSE_CASE_FLOWS\s*=/.test(src) || /id="flows"/.test(html))
    fail('Old plan layout (flows 3.N). Re-run the generate-use-case skill, then rebuild overview.html from the template.');
const USE_CASES = parseVar(src, 'USE_CASES', ucFile);
const CORE = parseVar(src, 'SCENARIOS', ucFile);
const hasMock = fs.existsSync(playFile);
const PLAY = hasMock ? parseVar(fs.readFileSync(playFile, 'utf8'), 'SCENARIO_PLAY', playFile) : [];
const SCS = CORE.map(s => ({ ...s, ...(PLAY.find(p => p.id === s.id) || { skip: 'no mock' }) }));
const playable = s => hasMock && !s.skip;

const esc = s => String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#x27;' }[c]));
const nn = ucId => ucId.slice(2).padStart(2, '0');
const href = s => play.replace(/\{(id|page|state)\}/g, (_, k) => encodeURIComponent(s[k]));
const ext = 'target="_blank" rel="noopener"';
const scsOf = ucId => SCS.filter(s => s.useCase === ucId);
const playCell = s => playable(s) ? `<a href="${esc(href(s))}" ${ext}>Play ↗</a>` : hasMock ? '<span class="aside">not in the mock</span>' : '';
const plural = (n, w) => `${n} ${w}${n === 1 ? '' : 's'}`;

// ---------------------------------------------------------------- "Open the mock" link on the Use cases heading
html = html.replace(/(<section class="slide" id="use-cases"[^>]*>\s*<h2>[\s\S]*?)(?: <a class="side-link"[^>]*>[^<]*<\/a>)?<\/h2>/,
    (_, h2) => `${h2}${hasMock ? ` <a class="side-link" href="${esc(mockIndex)}" ${ext}>Open the mock ↗</a>` : ''}</h2>`);

// ---------------------------------------------------------------- "Scenarios" view per use case
const I = '            ';
const panelOf = (uc, id) => {
    const scs = scsOf(uc.id);
    const open = `<div class="panel" role="region" tabindex="-1" id="${id}" aria-labelledby="${id}-tab" hidden>`;
    const note = `${I}    <!-- Generated by scripts/scenarios-panels.js from use-cases.js${hasMock ? ' and the mock\'s play file' : ''}. Don't hand-edit. -->`;
    const title = `${I}    <h4>Scenarios</h4>`;
    if (!scs.length) return `${open}\n${note}\n${title}\n${I}    <p class="muted">${esc(uc.none || 'No scenario for this use case.')}</p>\n${I}</div>`;
    const rows = scs.map(s => `${I}            <tr><td>${esc(s.title)}<br><span class="aside">${esc(s.expect[0] || '')}</span></td><td class="nowrap">${esc(s.story)}</td>${hasMock ? `<td class="nowrap">${playCell(s)}</td>` : ''}</tr>`);
    return `${open}\n${note}\n${title}\n${I}    <div class="table-wrap"><table>\n${I}        <thead><tr><th>Scenario</th><th>Story</th>${hasMock ? '<th></th>' : ''}</tr></thead><tbody>\n${rows.join('\n')}\n${I}        </tbody></table></div>\n${I}</div>`;
};
const missing = [];
for (const uc of USE_CASES) {
    const id = `uc-${nn(uc.id)}-sc`;
    const start = html.indexOf(`id="uc-${nn(uc.id)}"`);
    if (start < 0) { missing.push(uc.id); continue; }
    const end = (() => { const e = html.indexOf('</section>', start); return e < 0 ? html.length : e; })();
    let block = html.slice(start, end).replace(/\s*$/, '');
    // the panel is always the block's last child, so cut from it to the end
    const old = block.search(new RegExp(`\\s*<div class="panel"[^>]*id="${id}"`));
    if (old >= 0) block = block.slice(0, old);
    block = block.replace(new RegExp(`\\n[ \\t]*<button[^>]*id="${id}-tab"[^>]*>[^<]*</button>`), '');
    const button = `<button type="button" aria-expanded="false" aria-controls="${id}" id="${id}-tab">Scenarios (${scsOf(uc.id).length})</button>`;
    block = block.replace(/(<div class="views"[\s\S]*?)(\n[ \t]*<\/div>)/, `$1\n${I}    ${button}$2`);
    block += `\n${I}${panelOf(uc, id)}\n        `;
    html = html.slice(0, start) + block + html.slice(end);
}

fs.writeFileSync(overviewPath, html);
process.stdout.write(`Scenarios written into the use cases: ${plural(SCS.length, 'scenario')} in ${plural(USE_CASES.length, 'use case')}, ${hasMock ? `${SCS.filter(playable).length} playable in the mock` : 'no mock'}\n`);
USE_CASES.forEach(uc => process.stdout.write(`  ${uc.id} ${uc.title}: ${scsOf(uc.id).length}${hasMock ? ` (${scsOf(uc.id).filter(playable).length} playable)` : ''}\n`));
if (missing.length) fail(`No #uc-NN block in overview.html for use case(s): ${missing.join(', ')}`);
